### ISSUE TITLE
Customisable hash length

### ISSUE THREAD

**Issue by maxmilton** [sindresorhus/rev-hash#1]
I use gulp-rev and love it, makes cache busting super easy and it's fast.

One thing I would like though is an option to customise the hash length. Personally, I just like the look of a short hash on my file, 5 characters is great for me. I use this in small projects where the files change infrequently and the chance of a hash collision is extremely low.

**Comment by kevva** [comment]
I really think just slicing is a better option in this case than introducing a new option for this. Just do:

``` js
var fs = require('fs');
var revHash = require('rev-hash');
var buffer = fs.readFileSync('unicorn.png');

revHash(buffer).slice(0, 5);
//=> 'bb9d8'
```

And regarding the length in `gulp-rev`, see https://github.com/sindresorhus/gulp-rev/issues/102, https://github.com/sindresorhus/gulp-rev/pull/71, https://github.com/sindresorhus/gulp-rev/pull/5.

**Comment by maxmilton** [comment]
Great answer thank you very much, especially for the links!
