### ISSUE TITLE
different result between *nix(linux or mac-osx) and windows

### ISSUE THREAD

**Issue by Froguard** [sindresorhus/rev-hash#2]
hi, md5 hash result (10 characters) is different between *nix(linux or mac-osx) and windows,
could I do something options to unified it？waiting for your reply :smile:

**Comment by sindresorhus** [comment]
Make sure they're on the same and recent Node.js version. Some previous Node.js versions had differing behavior when hashing buffers.

Related: https://github.com/sindresorhus/gulp-rev/issues/178

**Comment by Froguard** [comment]
Okay,thanks!
